# 6.6.1.1 To specify the number of triples in the dataset
CONSTRUCT {
  <?_graph_uri> void:entities ?entities .
} WHERE {
  <?_graph_start>
    { SELECT (COUNT(DISTINCT ?s) AS ?entities) { ?s a [] } } 
    # count unique entities
  <?_graph_end>
}